# Generated by Django 5.1.1 on 2024-10-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('enseignant', 'Enseignant'), ('étudiant', 'Étudiant')], default='student', max_length=10),
            preserve_default=False,
        ),
    ]
